changes .env to jungle tesnet
edenia/Eden pull request #26
Opened 2022-08-19 20:01 UTC by fagomezra

2022-08-26 14:29 UTC, AngeloCG97 approved these changes
LGTM

2022-08-30 03:53 UTC, leisterfrancisco requested changes

2022-08-30 03:53 UTC, leisterfrancisco commented on .github/workflows/push-dev-environment.yaml
>                    NEXT_PUBLIC_TOKEN_PRECISION: 8
4

2022-08-30 03:53 UTC, leisterfrancisco commented on .github/workflows/push-dev-environment.yaml
> +                  NEXT_PUBLIC_APP_MINIMUM_DONATION_AMOUNT: 10.00000000 EOS
10.0000

2022-09-02 21:27 UTC, xavier506 approved these changes
LGTM

2022-09-02 21:29 UTC, leisterfrancisco approved these changes

2022-09-02 21:30 UTC, merged